### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by indirakalagara** [cloud-native-toolkit/terraform-aws-rosa#10]
Set defaults to variables:

- rosa-cluster_compute-machine-type
- machine-cidr
- service-cidr
- pod-cidr
- etcd-encryption
- dry-run to false 

Remove variables

- subnet_ids

Update cli command with 
- compute machine type
-  custom managed keys

**Comment by smatthyssen** [comment]
@indirakalagara can you please edit this title to have more description?  Also is it related to an Epic?

**Comment by indirakalagara** [comment]
In Release 1.3.0

- Updated rosa module by setting defaults to  service-cidr, pod-cidr
- Default value of dry-run set to false
