### ISSUE TITLE
Tammy would like to use a ROSA cluster with all the other modules

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/terraform-aws-rosa#6]
In order for the module to plug into the other modules it must define and implement the cluster interface in the module metadata. Need to add the `interfaces` value to the module.

```
name: aws-rosa
alias: cluster
interfaces:
- github.com/cloud-native-toolkit/automation-modules#cluster
...
```

The cluster interface is defined here - https://github.com/cloud-native-toolkit/software-everywhere/blob/main/interfaces/cluster.yaml

**Comment by indirakalagara** [comment]
Delivered via v1.3.0 release
