### ISSUE TITLE
The no_compute_nodes variable should be "compute nodes per zone" instead of total number of nodes

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/terraform-aws-rosa#7]

**Comment by indirakalagara** [comment]
Hello @seansund ,
Below are my observations for the number of compute nodes for rosa cluster creation.

As per ROSA CLI  

--compute-nodes int           Number of worker nodes to provision per zone. Single zone clusters need at least 2 nodes, **multizone clusters need at least 3 nodes. (default 2)**

In the module, the value for the compute-nodes is already passed. However,  The behavior of number of compute nodes is different in rosa comparing to IBM roks cluster

Although the command says - compute nodes per zone. In case of multizone, we have to provide this value as multiple of 3. 

For example , when I tried below cmd with compute_nodes = 5 , it failed with an error as below. 

rosa create cluster  --cluster-name ind-cluster --region ap-south-1 --version 4.9.15 **--compute-nodes 5 -**-machine-cidr 10.0.0.0/16 --service-cidr 172.30.0.0/16 --pod-cidr 10.128.0.0/14 --host-prefix 24 --etcd-encryption  --multi-az    

**E: Multi AZ clusters require that the number of compute nodes be a multiple of 3**

This means that the user has to pass the overall compute nodes per cluster in case of mutlizone, and it will be distributed  by dividing by 3. 

@rich-ehrhardt  Please provide your observations.

@Sivasaivm @faheemshai  FYI

**Comment by indirakalagara** [comment]
Updated code which takes input as number_of_compute_nodes per zone  For multizone cluster, the code will compute the number of nodes ,basically ( number_of_compute_nodes per zone) * 3
